const keywordMap = {
  "health surveillance": [],
  "data collection": [],
  "data monitoring": [],
  "health data analysis": [],
  "health indicators": [],
  "disaggregated data": [],
  "aggregated data": [],
  "root causes of disparities": [],
  "emerging health issues": [],
  "disproportionately affected populations": [],
  "community-informed assessment": [],
  "community health needs": [],
  "cross-sector data sharing": [],
  "social determinants of health": [],
  "inclusive survey design": [],
  "health equity": [],
  "community engagement": [],
  "participatory research": [],
  "community assets": [],
  "narrative": [],
  "community-based participatory research \ue081cbpr\ue082": [],
  "epidemiologic surveillance": [],
  "health trends": [],
  "data equity": [],
  "intersectional analysis": [],
  "vulnerable populations": [],
  "needs assessment": [],
  "asset mapping": [],
  "data democratization": [],
  "health informatics": [],
  "data interpretation": [],
  "early warning systems": [],
  "disparity monitoring": [],
  "health mapping": [],
  "risk stratification": [],
  "collaborative assessment": [],
  "spatial analysis": [],
  "community storytelling": [],
  "mixed-methods assessment": [],
  "health communication": [],
  "accessible information": [],
  "multisector collaboration": [],
  "culturally appropriate materials": [],
  "linguistically appropriate messaging": [],
  "stakeholder engagement": [],
  "two-way communication": [],
  "trust-building": [],
  "health literacy": [],
  "prevention strategies": [],
  "health promotion": [],
  "health status indicators": [],
  "policy, systems, and environmental change": [],
  "cross-sector collaboration": [],
  "multi-sectoral data": [],
  "narrative-based health data": [],
  "community-informed research": [],
  "root cause analysis": [],
  "community voice": [],
  "equity-centered assessment": [],
  "lived experience as data": [],
  "intersectoral analysis": [],
  "data triangulation": [],
  "culturally relevant assessment": [],
  "collaborative knowledge-building": [],
  "power analysis": [],
  "asset-based messaging": [],
  "narrative framing": [],
  "health equity policies": [],
  "policy education": [],
  "community-driven solutions": [],
  "authentic engagement": [],
  "strengths-based relationships": [],
  "inclusive coalitions": [],
  "multi-sector partnerships": [],
  "community-informed policies": [],
  "public health expertise": [],
  "historical injustice correction": [],
  "policy review and reform": [],
  "health impact assessment": [],
  "resilience-building": [],
  "cross-sector lawmaking": [],
  "health in all policies": [],
  "community-based planning": [],
  "preparedness strategies": [],
  "continuous policy evaluation": [],
  "systems-level change": [],
  "co-creation of laws and plans": [],
  "policy-level change": [],
  "environmental-level change": [],
  "health services access": [],
  "preventive care access": [],
  "whole-person care": [],
  "accessible health information": [],
  "health education resources": [],
  "multi-sector collaboration": [],
  "strategic communication": [],
  "timely communication": [],
  "accurate messaging": [],
  "targeted communication": [],
  "inclusive messaging": [],
  "culturally appropriate communication": [],
  "equity-focused communication": [],
  "avoiding harmful narratives": [],
  "community-centered communication": [],
  "communication equity": [],
  "population-specific outreach": [],
  "lifelong learning culture": [],
  "public health capacity-building": [],
  "strategic planning": [],
  "leadership development": [],
  "communication skills": [],
  "public health infrastructure": [],
  "organizational learning": [],
  "competency-based training": [],
  "data analysis": [],
  "threat identification": [],
  "health disparities": [],
  "health inequities": [],
  "cross-sector data inputs": [],
  "multi-sectoral collaboration": [],
  "economic determinants": [],
  "environmental determinants": [],
  "community health status": [],
  "population health monitoring": [],
  "equity-focused assessment": [],
  "health information dissemination": [],
  "accessible communication": [],
  "community-informed messaging": [],
  "health communication strategy": [],
  "resource development": [],
  "cross-sector partnerships": [],
  "public health outreach": [],
  "equity in messaging": [],
  "health literacy promotion": [],
  "lifelong learning": [],
  "public health workforce development": [],
  "knowledge translation": [],
  "practice-based evidence": [],
  "research-to-practice": [],
  "evidence-informed decision-making": [],
  "public health innovation": [],
  "equitable resource allocation": [],
  "public health funding": [],
  "resource distribution": [],
  "health systems improvement": [],
  "infrastructure investment": [],
  "building evidence base": [],
  "research integration": [],
  "strategic public health planing": [],
  "commission of social determinants of health": [],
  "structural determinants of social determinants of health inequities": [],
  "intermediary determinants of social determinants of health": [],
  "socieconomic and political context": [],
  "governance": [],
  "macroeconomic policies": [],
  "social policies": [],
  "public policies": [],
  "culture and societal values": [],
  "socieconomic position": [],
  "social class": [],
  "gender": [],
  "ethnicity": [],
  "racism": [],
  "social cohesion & social capital": [],
  "material circumstances": [],
  "behavior and biological factors": [],
  "psychological factors": [],
  "health system": [],
  "equity": [],
  "community needs and assets": [],
  "key influences on health": [],
  "data communication": [],
  "racial equity data": [],
  "data transparency": [],
  "cross-sectoral inputs": [],
  "multi-sector data integration": [],
  "equity-informed analysis": [],
  "health outcomes": [],
  "inclusive data practices": [],
  "health coalitions": [],
  "intersectoral collaboration": [],
  "diverse stakeholder engagement": [],
  "equity in policymaking": [],
  "policy analysis and reform": [],
  "health narratives": [],
  "data sharing": [],
  "cross-sector inputs": [],
  "root causes of health outcomes": [],
  "racial equity": [],
  "health promotion strategies": [],
  "asset-based communication": [],
  "multisector coalitions": [],
  "authentic community engagement": [],
  "inclusive partnerships": [],
  "community-informed solutions": [],
  "policy development": [],
  "policy equity": [],
  "correcting historical injustices": [],
  "community resilience policies": [],
  "cross-sector policy collaboration": [],
  "health improvement plans": [],
  "health service access": [],
  "workforce development": [],
  "cultural humility": [],
  "public health pipeline": [],
  "quality improvement": [],
  "research-practice integration": [],
  "community-based research": [],
  "organizational infrastructure": [],
  "public health governance": [],
  "ethical leadership": [],
  "resource management": [],
  "commitment to health and racial equity": [],
  "commitment": [],
  "transparency": [],
  "multi-method data use": [],
  "data visualization": [],
  "climate-related work assessment": [],
  "qualitative methods": [],
  "quantitative methods": [],
  "key informant interviews": [],
  "grounded theory": [],
  "thematic analysis": [],
  "public health solutions": [],
  "public health -informed policy": [],
  "inform policy development": [],
  "policy evaluation": [],
  "health policy development": [],
  "policy and law alignment": [],
  "equity in policy": [],
  "public health in climate-related work": [],
  "collaborative governance": [],
  "strategic policy planning": [],
  "public health education": [],
  "mixed methods (qualitative, quantitative, lived experience)": [],
  "data-informed decision-making": [],
  "health systems infrastructure": [],
  "organizational capacity": [],
  "system-level understanding": [],
  "public health system roles": [],
  "evidence base building": [],
  "leadership in public health": [],
  "infrastructure development": [],
  "climate change": [],
  "assessment": [],
  "climate impact preparedness": [],
  "emergency preparedness planning": [],
  "stretegic plan": [],
  "climate change training": [],
  "economic determinants of health": [],
  "environmental determinants of health": [],
  "community health assessment": [],
  "interagency data integration": [],
  "multi-source data utilization": [],
  "public health communication": [],
  "health education": [],
  "health equity messaging": [],
  "culturally sensitive communication": [],
  "inclusive health communication": [],
  "counteracting harmful narratives": [],
  "equity-centered communication": [],
  "research-to-practice integration": [],
  "practice-based insights": [],
  "public health research": [],
  "public health evidence base": [],
  "health systems support": [],
  "maternal morbidity": [],
  "maternal mortality": [],
  "literature review": [],
  "definitions": [],
  "causes": [],
  "gaps in data": [],
  "datasets available": [],
  "maternal vulnerability": [],
  "vulnerability index": [],
  "health needs": [],
  "health status": [],
  "key health influences": [],
  "health narrative": [],
  "community members as experts": [],
  "community partnerships": [],
  "accurate communication": [],
  "communication channels (e.g., social media, mass media, peer networks)": [],
  "health promotion messaging": [],
  "linguistically appropriate communication": [],
  "culturally resonant materials": [],
  "stakeholder collaboration": [],
  "community influencers": [],
  "public health quality improvement": [],
  "culture of quality": [],
  "qualitative data": [],
  "quantitative data": [],
  "public health practice": [],
  "regional analysis": [],
  "perceptions of public health": [],
  "regional findings": [],
  "familiarity of lhd": [],
  "knowledge of lhd": [],
  "correlation": [],
  "health monitoring": [],
  "epidemiologic identification": [],
  "emerging health threats": [],
  "racial health disparities": [],
  "innovative data methods": [],
  "public health technologies": [],
  "multisector data integration": [],
  "data-driven equity strategies": [],
  "injury prevention": [],
  "health equity analysis": [],
  "predictive analytics in public health": [],
  "data storytelling": [],
  "public health policy": [],
  "policy input": [],
  "accessible health communication": [],
  "narrative change": [],
  "equity-focused policy": [],
  "policy co-creation": [],
  "community-informed policymaking": [],
  "inclusive communication strategies": [],
  "public health planning": [],
  "upstream public health policy": [],
  "health justice narratives": [],
  "public health assurance": [],
  "culturally competent workforce": [],
  "strategic public health leadership": [],
  "health equity workforce": [],
  "academic partnerships": [],
  "framing": [],
  "small number messaging": [],
  "template": [],
  "small sample size": [],
  "statistical issues": [],
  "reduced statistical power": [],
  "wider confidence intervals": []
};
